### ISSUE TITLE
Crash with heatmap 30,000 x 30,000 

### ISSUE THREAD

**Issue by viktorskv** [Arction/javascript-charts-performance-comparison-heatmaps#2]
I'm trying to run this demo but seeing a crash when setting 30,000 x 30,000 size

my config
```
var BENCHMARK_CONFIG = (function (t) {
  "use strict";
  return {
    columns: 30000,
    rows: 30000,
    refreshData: false,
    scrollData: false,
    axisTicksEnabled: true,
  };
})();
```

output 

![image](https://user-images.githubusercontent.com/55160056/211157274-e68a4e28-f38c-4dbb-a9d5-b0f83fa9f796.png)

what am I doing wrong?

**Comment by Snekw** [comment]
Large heatmaps have limitations on Chrome (and other chromium based browsers) where the amount of memory a single tab can use is limited to ~3GB. This limitation doesn't exist on FireFox and the large heatmap tests on this repository were all run using FireFox.

**Comment by viktorskv** [comment]
It works in Firefox. Bit slow to first show, maybe 20-30 seconds but no crashes or errors. Impressive

I think for us its better to resize heatmap data on the server as problem is 30 second startup time and to send all the data to client is too long. Do you have a demo for this?

Thanks for quick help

**Comment by Snekw** [comment]
We currently don't have any demos for data transfers from server to client for heatmap data. Currently the only demo with server to client data transfers is our trading showcase https://github.com/Arction/lcjs-showcase-trading.
